!SESSION 2017-02-14 18:39:34.236 -----------------------------------------------
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=tr_TR
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.egit.ui 2 0 2017-02-14 18:46:21.232
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\SaWLeaDeR'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.eclipse.mylyn.tasks.core 4 0 2017-02-14 18:46:44.551
!MESSAGE Notification failed for: org.eclipse.mylyn.internal.tasks.core.TaskActivityManager$1@795de565
!STACK 0
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at org.eclipse.mylyn.internal.tasks.core.TaskActivityManager.reloadPlanningData(TaskActivityManager.java:210)
	at org.eclipse.mylyn.internal.tasks.core.TaskActivityManager$1.containersChanged(TaskActivityManager.java:95)
	at org.eclipse.mylyn.internal.tasks.core.TaskList.fireDelta(TaskList.java:273)
	at org.eclipse.mylyn.internal.tasks.core.TaskList.notifyElementsChanged(TaskList.java:495)
	at org.eclipse.mylyn.internal.tasks.core.TaskJobFactory$1.done(TaskJobFactory.java:140)
	at org.eclipse.core.internal.jobs.JobListeners$3.notify(JobListeners.java:42)
	at org.eclipse.core.internal.jobs.JobListeners.doNotify(JobListeners.java:106)
	at org.eclipse.core.internal.jobs.JobListeners.done(JobListeners.java:144)
	at org.eclipse.core.internal.jobs.JobManager.endJob(JobManager.java:694)
	at org.eclipse.core.internal.jobs.WorkerPool.endJob(WorkerPool.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:72)
!SESSION 2017-02-15 10:54:23.437 -----------------------------------------------
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=tr_TR
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.osgi 2 0 2017-02-15 10:55:40.341
!MESSAGE While loading class "org.eclipse.egit.ui.internal.ConfigurationChecker$1$1", thread "Thread[Worker-1,5,main]" timed out waiting (5139ms) for thread "Thread[main,6,main]" to finish starting bundle "org.eclipse.egit.ui_4.4.1.201607150455-r [124]". To avoid deadlock, thread "Thread[Worker-1,5,main]" is proceeding but "org.eclipse.egit.ui.internal.ConfigurationChecker$1$1" may not be fully initialized.
!STACK 0
org.osgi.framework.BundleException: Unable to acquire the state change lock for the module: osgi.identity; type="osgi.bundle"; version:Version="4.4.1.201607150455-r"; osgi.identity="org.eclipse.egit.ui"; singleton:="true" [id=124] STARTED [STARTED]
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:337)
	at org.eclipse.osgi.container.Module.start(Module.java:401)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:470)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:529)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:325)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.egit.ui.internal.ConfigurationChecker$1.run(ConfigurationChecker.java:45)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.util.concurrent.TimeoutException: Timeout after waiting 5 seconds to acquire the lock.
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:334)
	... 13 more
Root exception:
java.util.concurrent.TimeoutException: Timeout after waiting 5 seconds to acquire the lock.
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:334)
	at org.eclipse.osgi.container.Module.start(Module.java:401)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:470)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:529)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:325)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.egit.ui.internal.ConfigurationChecker$1.run(ConfigurationChecker.java:45)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.egit.ui 2 0 2017-02-15 10:56:39.068
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\SaWLeaDeR'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.
!SESSION 2017-02-15 11:04:43.098 -----------------------------------------------
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=tr_TR
Framework arguments:  -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product -data file:/C:/Users/SaWLeaDeR/workspace/ -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.egit.ui 2 0 2017-02-15 11:05:09.699
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\SaWLeaDeR'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.
!SESSION 2017-02-15 11:06:59.774 -----------------------------------------------
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=tr_TR
Framework arguments:  -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -data file:/C:/Users/SaWLeaDeR/workspace/ -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.egit.ui 2 0 2017-02-15 11:07:21.611
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\SaWLeaDeR'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.python.pydev.shared_core 1 1 2017-02-15 11:07:27.915
!MESSAGE Unable to track file that does not exist: C:\Python27\DLLs
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\DLLs
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-15 11:07:27.926
!MESSAGE Unable to track file that does not exist: C:\Python27\lib
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-15 11:07:27.934
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\lib-tk
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\lib-tk
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-15 11:07:27.942
!MESSAGE Unable to track file that does not exist: C:\Python27
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-15 11:07:27.950
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\site-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\site-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2017-02-15 11:07:58.222
!MESSAGE java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:312)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:278)
	at org.python.pydev.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:329)
	at org.python.pydev.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:95)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:68)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:44)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:390)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SynchSystemModulesManager.java:173)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.updateStructures(SynchSystemModulesManager.java:252)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:238)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:310)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 15 more

!ENTRY org.epic.perleditor 4 0 2017-02-15 11:08:10.130
!MESSAGE Failed to execute command line: "perl" "-v"
!STACK 0
java.io.IOException: Cannot run program "perl" (in directory "."): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:106)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:71)
	at org.epic.core.util.PerlExecutor.execute(PerlExecutor.java:100)
	at org.epic.perleditor.PerlEditorPlugin.checkForPerlInterpreter(PerlEditorPlugin.java:262)
	at org.epic.perleditor.PerlEditorPlugin.requirePerlInterpreter(PerlEditorPlugin.java:235)
	at org.epic.core.builders.PerlBuilder.buildImpl(PerlBuilder.java:77)
	at org.epic.core.builders.PerlBuilder.build(PerlBuilder.java:63)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 21 more

!ENTRY org.epic.perleditor 4 0 2017-02-15 11:08:50.168
!MESSAGE Failed to execute command line: "perl" "-v"
!STACK 0
java.io.IOException: Cannot run program "perl" (in directory "."): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:106)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:71)
	at org.epic.core.util.PerlExecutor.execute(PerlExecutor.java:100)
	at org.epic.perleditor.PerlEditorPlugin.checkForPerlInterpreter(PerlEditorPlugin.java:262)
	at org.epic.perleditor.PerlEditorPlugin.requirePerlInterpreter(PerlEditorPlugin.java:235)
	at org.epic.core.builders.PerlBuilder.buildImpl(PerlBuilder.java:77)
	at org.epic.core.builders.PerlBuilder.build(PerlBuilder.java:63)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 21 more

!ENTRY org.epic.perleditor 4 0 2017-02-15 11:08:50.201
!MESSAGE Failed to execute command line: "perl" "-v"
!STACK 0
java.io.IOException: Cannot run program "perl" (in directory "."): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:106)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:71)
	at org.epic.core.util.PerlExecutor.execute(PerlExecutor.java:100)
	at org.epic.perleditor.PerlEditorPlugin.checkForPerlInterpreter(PerlEditorPlugin.java:262)
	at org.epic.perleditor.PerlEditorPlugin.requirePerlInterpreter(PerlEditorPlugin.java:235)
	at org.epic.core.builders.PerlBuilder.buildImpl(PerlBuilder.java:77)
	at org.epic.core.builders.PerlBuilder.build(PerlBuilder.java:63)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 21 more
!SESSION 2017-02-15 17:21:00.488 -----------------------------------------------
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=tr_TR
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.osgi 2 0 2017-02-15 17:21:50.030
!MESSAGE While loading class "org.eclipse.egit.ui.internal.ConfigurationChecker$1$1", thread "Thread[Worker-0,5,main]" timed out waiting (5048ms) for thread "Thread[main,6,main]" to finish starting bundle "org.eclipse.egit.ui_4.4.1.201607150455-r [124]". To avoid deadlock, thread "Thread[Worker-0,5,main]" is proceeding but "org.eclipse.egit.ui.internal.ConfigurationChecker$1$1" may not be fully initialized.
!STACK 0
org.osgi.framework.BundleException: Unable to acquire the state change lock for the module: osgi.identity; type="osgi.bundle"; version:Version="4.4.1.201607150455-r"; osgi.identity="org.eclipse.egit.ui"; singleton:="true" [id=124] STARTED [STARTED]
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:337)
	at org.eclipse.osgi.container.Module.start(Module.java:401)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:470)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:529)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:325)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.egit.ui.internal.ConfigurationChecker$1.run(ConfigurationChecker.java:45)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.util.concurrent.TimeoutException: Timeout after waiting 5 seconds to acquire the lock.
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:334)
	... 13 more
Root exception:
java.util.concurrent.TimeoutException: Timeout after waiting 5 seconds to acquire the lock.
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:334)
	at org.eclipse.osgi.container.Module.start(Module.java:401)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:470)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:529)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:325)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.egit.ui.internal.ConfigurationChecker$1.run(ConfigurationChecker.java:45)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.egit.ui 2 0 2017-02-15 17:23:45.096
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\SaWLeaDeR'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.python.pydev.shared_core 1 1 2017-02-15 17:24:15.158
!MESSAGE Unable to track file that does not exist: C:\Python27\DLLs
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\DLLs
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-15 17:24:15.279
!MESSAGE Unable to track file that does not exist: C:\Python27\lib
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-15 17:24:15.320
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\lib-tk
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\lib-tk
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-15 17:24:15.343
!MESSAGE Unable to track file that does not exist: C:\Python27
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-15 17:24:15.361
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\site-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\site-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2017-02-15 17:24:46.005
!MESSAGE java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:312)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:278)
	at org.python.pydev.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:329)
	at org.python.pydev.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:95)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:68)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:44)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:390)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SynchSystemModulesManager.java:173)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.updateStructures(SynchSystemModulesManager.java:252)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:238)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:310)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 15 more

!ENTRY org.python.pydev.shared_core 4 4 2017-02-15 17:27:37.622
!MESSAGE Info: Rebuilding internal caches: C:\Users\SaWLeaDeR\workspace\.metadata\.plugins\org.eclipse.core.resources\.projects\helloworldpy\com.python.pydev.analysis\AdditionalProjectInterpreterInfo.pydevinfo (Expected error to be provided and got no error!)

!ENTRY org.epic.perleditor 4 0 2017-02-15 17:28:03.279
!MESSAGE Failed to execute command line: "perl" "-v"
!STACK 0
java.io.IOException: Cannot run program "perl" (in directory "."): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:106)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:71)
	at org.epic.core.util.PerlExecutor.execute(PerlExecutor.java:100)
	at org.epic.perleditor.PerlEditorPlugin.checkForPerlInterpreter(PerlEditorPlugin.java:262)
	at org.epic.perleditor.PerlEditorPlugin.requirePerlInterpreter(PerlEditorPlugin.java:235)
	at org.epic.core.builders.PerlBuilder.buildImpl(PerlBuilder.java:77)
	at org.epic.core.builders.PerlBuilder.build(PerlBuilder.java:63)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 21 more

!ENTRY org.eclipse.ui 4 0 2017-02-15 17:33:45.752
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.IllegalStateException: Need an underlying widget to be able to set the input.(Has the widget been disposed?))
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4211)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3827)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.ui.internal.handlers.WizardHandler$Import.executeHandler(WizardHandler.java:158)
	at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:290)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:282)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:264)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:353)
	at org.eclipse.ui.internal.actions.CommandAction.runWithEvent(CommandAction.java:155)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4236)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3824)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
Caused by: java.lang.IllegalStateException: Need an underlying widget to be able to set the input.(Has the widget been disposed?)
	at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1687)
	at org.eclipse.ui.internal.about.AboutPluginsPage.lambda$1(AboutPluginsPage.java:359)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	... 50 more

!ENTRY org.python.pydev.shared_core 4 4 2017-02-15 17:34:10.427
!MESSAGE Info: Rebuilding internal caches: C:\Users\SaWLeaDeR\workspace\.metadata\.plugins\org.eclipse.core.resources\.projects\Phyton Test\com.python.pydev.analysis\AdditionalProjectInterpreterInfo.pydevinfo (Expected error to be provided and got no error!)

!ENTRY org.eclipse.epp.logging.aeri.ide 2 11 2017-02-15 17:34:29.418
!MESSAGE Updating the index from remote ‘https://www.eclipse.org/downloads/download.php?r=1&file=/technology/epp/logging/problems.zip’ failed with exception: java.lang.NullPointerException ; version: 2.0.3.v20161205-0933
!STACK 0
org.eclipse.epp.logging.aeri.core.util.Logs$LogTraceException
	at org.eclipse.epp.logging.aeri.core.util.Logs$LogTraceException.newTrace(Logs.java:387)
	at org.eclipse.epp.logging.aeri.core.util.Logs.log(Logs.java:134)
	at org.eclipse.epp.internal.logging.aeri.ide.server.mars.ProblemsDatabaseProblemsHistory$UpdateIndexJob.run(ProblemsDatabaseProblemsHistory.java:289)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.debug.core 4 125 2017-02-15 17:34:39.185
!MESSAGE Exception occurred executing command line.
!STACK 0
java.io.IOException: Cannot run program "C:\Python27\python.exe" (in directory "C:\Users\SaWLeaDeR\workspace\Phyton Test"): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.eclipse.debug.core.DebugPlugin.exec(DebugPlugin.java:881)
	at org.python.pydev.debug.ui.launching.PythonRunner.createProcess(PythonRunner.java:287)
	at org.python.pydev.debug.ui.launching.PythonRunner.doIt(PythonRunner.java:247)
	at org.python.pydev.debug.ui.launching.PythonRunner.run(PythonRunner.java:114)
	at org.python.pydev.debug.ui.launching.AbstractLaunchConfigurationDelegate.launch(AbstractLaunchConfigurationDelegate.java:109)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 12 more

!ENTRY org.epic.perleditor 4 0 2017-02-15 18:28:59.104
!MESSAGE Failed to execute command line: "perl" "-v"
!STACK 0
java.io.IOException: Cannot run program "perl" (in directory "."): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:106)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:71)
	at org.epic.core.util.PerlExecutor.execute(PerlExecutor.java:100)
	at org.epic.perleditor.PerlEditorPlugin.checkForPerlInterpreter(PerlEditorPlugin.java:262)
	at org.epic.perleditor.PerlEditorPlugin.requirePerlInterpreter(PerlEditorPlugin.java:235)
	at org.epic.core.builders.PerlBuilder.buildImpl(PerlBuilder.java:77)
	at org.epic.core.builders.PerlBuilder.build(PerlBuilder.java:63)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 21 more

!ENTRY org.epic.perleditor 4 0 2017-02-15 18:29:04.124
!MESSAGE Failed to execute command line: "perl" "-v"
!STACK 0
java.io.IOException: Cannot run program "perl" (in directory "."): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:106)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:71)
	at org.epic.core.util.PerlExecutor.execute(PerlExecutor.java:100)
	at org.epic.perleditor.PerlEditorPlugin.checkForPerlInterpreter(PerlEditorPlugin.java:262)
	at org.epic.perleditor.PerlEditorPlugin.requirePerlInterpreter(PerlEditorPlugin.java:235)
	at org.epic.core.builders.PerlBuilder.buildImpl(PerlBuilder.java:77)
	at org.epic.core.builders.PerlBuilder.build(PerlBuilder.java:63)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 21 more
!SESSION 2017-02-17 21:39:49.184 -----------------------------------------------
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=tr_TR
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.egit.ui 2 0 2017-02-17 21:40:35.082
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\SaWLeaDeR'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.python.pydev.shared_core 1 1 2017-02-17 21:40:35.202
!MESSAGE Unable to track file that does not exist: C:\Python27\DLLs
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\DLLs
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-17 21:40:35.583
!MESSAGE Unable to track file that does not exist: C:\Python27\lib
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-17 21:40:35.646
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\lib-tk
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\lib-tk
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-17 21:40:35.657
!MESSAGE Unable to track file that does not exist: C:\Python27
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-17 21:40:35.666
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\site-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\site-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2017-02-17 21:41:05.809
!MESSAGE java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:312)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:278)
	at org.python.pydev.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:329)
	at org.python.pydev.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:95)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:68)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:44)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:390)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SynchSystemModulesManager.java:173)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.updateStructures(SynchSystemModulesManager.java:252)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:238)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:310)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 15 more
!SESSION 2017-02-17 21:43:13.513 -----------------------------------------------
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=tr_TR
Framework arguments:  -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product -data file:/C:/Users/SaWLeaDeR/workspace/ -product org.eclipse.epp.package.java.product

!ENTRY org.python.pydev.shared_core 1 1 2017-02-17 21:43:42.917
!MESSAGE Unable to track file that does not exist: C:\Python27\DLLs
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\DLLs
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.egit.ui 2 0 2017-02-17 21:43:43.292
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\SaWLeaDeR'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.python.pydev.shared_core 1 1 2017-02-17 21:43:43.658
!MESSAGE Unable to track file that does not exist: C:\Python27\lib
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-17 21:43:43.737
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\lib-tk
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\lib-tk
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-17 21:43:44.108
!MESSAGE Unable to track file that does not exist: C:\Python27
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-17 21:43:44.343
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\site-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\site-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2017-02-17 21:44:14.590
!MESSAGE java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:312)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:278)
	at org.python.pydev.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:329)
	at org.python.pydev.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:95)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:68)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:44)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:390)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SynchSystemModulesManager.java:173)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.updateStructures(SynchSystemModulesManager.java:252)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:238)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:310)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 15 more
!SESSION 2017-02-18 13:46:53.925 -----------------------------------------------
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=tr_TR
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.osgi 2 0 2017-02-18 13:48:03.066
!MESSAGE While loading class "org.eclipse.egit.ui.internal.ConfigurationChecker$1$1", thread "Thread[Worker-0,5,main]" timed out waiting (5086ms) for thread "Thread[main,6,main]" to finish starting bundle "org.eclipse.egit.ui_4.4.1.201607150455-r [124]". To avoid deadlock, thread "Thread[Worker-0,5,main]" is proceeding but "org.eclipse.egit.ui.internal.ConfigurationChecker$1$1" may not be fully initialized.
!STACK 0
org.osgi.framework.BundleException: Unable to acquire the state change lock for the module: osgi.identity; type="osgi.bundle"; version:Version="4.4.1.201607150455-r"; osgi.identity="org.eclipse.egit.ui"; singleton:="true" [id=124] STARTED [STARTED]
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:337)
	at org.eclipse.osgi.container.Module.start(Module.java:401)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:470)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:529)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:325)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.egit.ui.internal.ConfigurationChecker$1.run(ConfigurationChecker.java:45)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.util.concurrent.TimeoutException: Timeout after waiting 5 seconds to acquire the lock.
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:334)
	... 13 more
Root exception:
java.util.concurrent.TimeoutException: Timeout after waiting 5 seconds to acquire the lock.
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:334)
	at org.eclipse.osgi.container.Module.start(Module.java:401)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:470)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:529)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:325)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.egit.ui.internal.ConfigurationChecker$1.run(ConfigurationChecker.java:45)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-18 13:48:59.462
!MESSAGE Unable to track file that does not exist: C:\Python27\DLLs
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\DLLs
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-18 13:48:59.814
!MESSAGE Unable to track file that does not exist: C:\Python27\lib
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-18 13:48:59.825
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\lib-tk
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\lib-tk
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-18 13:48:59.834
!MESSAGE Unable to track file that does not exist: C:\Python27
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-18 13:48:59.845
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\site-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\site-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.egit.ui 2 0 2017-02-18 13:48:59.944
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\SaWLeaDeR'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.python.pydev.shared_core 4 4 2017-02-18 13:49:32.504
!MESSAGE java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:312)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:278)
	at org.python.pydev.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:329)
	at org.python.pydev.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:95)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:68)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:44)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:390)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SynchSystemModulesManager.java:173)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.updateStructures(SynchSystemModulesManager.java:252)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:238)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:310)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 15 more

!ENTRY org.epic.perleditor 4 0 2017-02-18 13:52:19.440
!MESSAGE Failed to execute command line: "perl" "-v"
!STACK 0
java.io.IOException: Cannot run program "perl" (in directory "."): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:106)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:71)
	at org.epic.core.util.PerlExecutor.execute(PerlExecutor.java:100)
	at org.epic.perleditor.PerlEditorPlugin.checkForPerlInterpreter(PerlEditorPlugin.java:262)
	at org.epic.perleditor.PerlEditorPlugin.requirePerlInterpreter(PerlEditorPlugin.java:235)
	at org.epic.core.builders.PerlBuilder.buildImpl(PerlBuilder.java:77)
	at org.epic.core.builders.PerlBuilder.build(PerlBuilder.java:63)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 21 more

!ENTRY org.epic.perleditor 4 0 2017-02-18 13:52:22.997
!MESSAGE Failed to execute command line: "perl" "-v"
!STACK 0
java.io.IOException: Cannot run program "perl" (in directory "."): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:106)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:71)
	at org.epic.core.util.PerlExecutor.execute(PerlExecutor.java:100)
	at org.epic.perleditor.PerlEditorPlugin.checkForPerlInterpreter(PerlEditorPlugin.java:262)
	at org.epic.perleditor.PerlEditorPlugin.requirePerlInterpreter(PerlEditorPlugin.java:235)
	at org.epic.core.builders.PerlBuilder.buildImpl(PerlBuilder.java:77)
	at org.epic.core.builders.PerlBuilder.build(PerlBuilder.java:63)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 21 more

!ENTRY org.epic.perleditor 4 0 2017-02-18 13:52:23.211
!MESSAGE Failed to execute command line: "perl" "-v"
!STACK 0
java.io.IOException: Cannot run program "perl" (in directory "."): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:106)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:71)
	at org.epic.core.util.PerlExecutor.execute(PerlExecutor.java:100)
	at org.epic.perleditor.PerlEditorPlugin.checkForPerlInterpreter(PerlEditorPlugin.java:262)
	at org.epic.perleditor.PerlEditorPlugin.requirePerlInterpreter(PerlEditorPlugin.java:235)
	at org.epic.core.builders.PerlBuilder.buildImpl(PerlBuilder.java:77)
	at org.epic.core.builders.PerlBuilder.build(PerlBuilder.java:63)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 21 more

!ENTRY org.eclipse.jdt.core 4 4 2017-02-18 13:52:23.644
!MESSAGE JavaBuilder handling ImageBuilderInternalException while building: homework6
!STACK 1
org.eclipse.core.runtime.CoreException: Could not write file: C:\Users\SaWLeaDeR\workspace\homework6\bin\homework6.
	at org.eclipse.core.internal.filesystem.Policy.error(Policy.java:49)
	at org.eclipse.core.internal.filesystem.Policy.error(Policy.java:44)
	at org.eclipse.core.internal.filesystem.local.LocalFile.checkTargetIsNotWritable(LocalFile.java:95)
	at org.eclipse.core.internal.filesystem.local.LocalFile.mkdir(LocalFile.java:309)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.write(FileSystemResourceManager.java:1194)
	at org.eclipse.core.internal.resources.Folder.internalCreate(Folder.java:172)
	at org.eclipse.core.internal.resources.Folder.create(Folder.java:105)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.createFolder(AbstractImageBuilder.java:473)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder$1.visit(AbstractImageBuilder.java:257)
	at org.eclipse.core.internal.resources.Resource$1.visitElement(Resource.java:84)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:82)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:129)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:52)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.addAllSourceFiles(AbstractImageBuilder.java:222)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:52)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:256)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:175)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
!SUBENTRY 1 org.eclipse.core.filesystem 4 272 2017-02-18 13:52:23.647
!MESSAGE Could not write file: C:\Users\SaWLeaDeR\workspace\homework6\bin\homework6.

!ENTRY org.epic.perleditor 4 0 2017-02-18 13:57:12.912
!MESSAGE Failed to execute command line: "perl" "-v"
!STACK 0
java.io.IOException: Cannot run program "perl" (in directory "."): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:106)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:71)
	at org.epic.core.util.PerlExecutor.execute(PerlExecutor.java:100)
	at org.epic.perleditor.PerlEditorPlugin.checkForPerlInterpreter(PerlEditorPlugin.java:262)
	at org.epic.perleditor.PerlEditorPlugin.requirePerlInterpreter(PerlEditorPlugin.java:235)
	at org.epic.core.builders.PerlBuilder.buildImpl(PerlBuilder.java:77)
	at org.epic.core.builders.PerlBuilder.build(PerlBuilder.java:63)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 21 more
!SESSION 2017-02-18 15:10:53.308 -----------------------------------------------
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=tr_TR
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.egit.ui 2 0 2017-02-18 15:11:33.381
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\SaWLeaDeR'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.python.pydev.shared_core 1 1 2017-02-18 15:11:57.755
!MESSAGE Unable to track file that does not exist: C:\Python27\DLLs
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\DLLs
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-18 15:11:58.391
!MESSAGE Unable to track file that does not exist: C:\Python27\lib
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-18 15:11:58.520
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\lib-tk
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\lib-tk
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-18 15:11:58.777
!MESSAGE Unable to track file that does not exist: C:\Python27
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-18 15:11:58.989
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\site-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\site-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2017-02-18 15:12:29.286
!MESSAGE java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:312)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:278)
	at org.python.pydev.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:329)
	at org.python.pydev.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:95)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:68)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:44)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:390)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SynchSystemModulesManager.java:173)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.updateStructures(SynchSystemModulesManager.java:252)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:238)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:310)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 15 more
!SESSION 2017-02-18 17:55:36.957 -----------------------------------------------
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=tr_TR
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.osgi 2 0 2017-02-18 17:55:59.411
!MESSAGE While loading class "org.eclipse.egit.ui.internal.ConfigurationChecker$1$1", thread "Thread[Worker-1,5,main]" timed out waiting (5504ms) for thread "Thread[main,6,main]" to finish starting bundle "org.eclipse.egit.ui_4.4.1.201607150455-r [124]". To avoid deadlock, thread "Thread[Worker-1,5,main]" is proceeding but "org.eclipse.egit.ui.internal.ConfigurationChecker$1$1" may not be fully initialized.
!STACK 0
org.osgi.framework.BundleException: Unable to acquire the state change lock for the module: osgi.identity; type="osgi.bundle"; version:Version="4.4.1.201607150455-r"; osgi.identity="org.eclipse.egit.ui"; singleton:="true" [id=124] STARTED [STARTED]
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:337)
	at org.eclipse.osgi.container.Module.start(Module.java:401)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:470)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:529)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:325)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.egit.ui.internal.ConfigurationChecker$1.run(ConfigurationChecker.java:45)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.util.concurrent.TimeoutException: Timeout after waiting 5 seconds to acquire the lock.
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:334)
	... 13 more
Root exception:
java.util.concurrent.TimeoutException: Timeout after waiting 5 seconds to acquire the lock.
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:334)
	at org.eclipse.osgi.container.Module.start(Module.java:401)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:470)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:529)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:325)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.egit.ui.internal.ConfigurationChecker$1.run(ConfigurationChecker.java:45)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.egit.ui 2 0 2017-02-18 17:56:30.750
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\SaWLeaDeR'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.python.pydev.shared_core 1 1 2017-02-18 17:56:45.699
!MESSAGE Unable to track file that does not exist: C:\Python27\DLLs
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\DLLs
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-18 17:56:45.843
!MESSAGE Unable to track file that does not exist: C:\Python27\lib
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-18 17:56:45.910
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\lib-tk
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\lib-tk
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-18 17:56:45.924
!MESSAGE Unable to track file that does not exist: C:\Python27
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-18 17:56:45.932
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\site-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\site-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2017-02-18 17:57:16.354
!MESSAGE java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:312)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:278)
	at org.python.pydev.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:329)
	at org.python.pydev.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:95)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:68)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:44)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:390)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SynchSystemModulesManager.java:173)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.updateStructures(SynchSystemModulesManager.java:252)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:238)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:310)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 15 more
!SESSION 2017-02-18 19:47:13.054 -----------------------------------------------
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=tr_TR
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.osgi 2 0 2017-02-18 19:48:34.679
!MESSAGE While loading class "org.eclipse.egit.ui.internal.ConfigurationChecker$1$1", thread "Thread[Worker-0,5,main]" timed out waiting (5031ms) for thread "Thread[main,6,main]" to finish starting bundle "org.eclipse.egit.ui_4.4.1.201607150455-r [124]". To avoid deadlock, thread "Thread[Worker-0,5,main]" is proceeding but "org.eclipse.egit.ui.internal.ConfigurationChecker$1$1" may not be fully initialized.
!STACK 0
org.osgi.framework.BundleException: Unable to acquire the state change lock for the module: osgi.identity; type="osgi.bundle"; version:Version="4.4.1.201607150455-r"; osgi.identity="org.eclipse.egit.ui"; singleton:="true" [id=124] STARTED [STARTED]
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:337)
	at org.eclipse.osgi.container.Module.start(Module.java:401)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:470)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:529)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:325)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.egit.ui.internal.ConfigurationChecker$1.run(ConfigurationChecker.java:45)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.util.concurrent.TimeoutException: Timeout after waiting 5 seconds to acquire the lock.
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:334)
	... 13 more
Root exception:
java.util.concurrent.TimeoutException: Timeout after waiting 5 seconds to acquire the lock.
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:334)
	at org.eclipse.osgi.container.Module.start(Module.java:401)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:470)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:529)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:325)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.egit.ui.internal.ConfigurationChecker$1.run(ConfigurationChecker.java:45)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.egit.ui 2 0 2017-02-18 19:49:34.375
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\SaWLeaDeR'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.python.pydev.shared_core 1 1 2017-02-18 19:49:58.421
!MESSAGE Unable to track file that does not exist: C:\Python27\DLLs
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\DLLs
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-18 19:49:58.478
!MESSAGE Unable to track file that does not exist: C:\Python27\lib
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-18 19:49:58.546
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\lib-tk
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\lib-tk
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-18 19:49:58.592
!MESSAGE Unable to track file that does not exist: C:\Python27
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-18 19:49:58.601
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\site-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\site-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2017-02-18 19:50:28.900
!MESSAGE java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:312)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:278)
	at org.python.pydev.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:329)
	at org.python.pydev.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:95)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:68)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:44)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:390)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SynchSystemModulesManager.java:173)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.updateStructures(SynchSystemModulesManager.java:252)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:238)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:310)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 15 more
!SESSION 2017-02-21 18:21:19.684 -----------------------------------------------
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=tr_TR
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.egit.ui 2 0 2017-02-21 18:22:50.855
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\SaWLeaDeR'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.python.pydev.shared_core 1 1 2017-02-21 18:24:12.765
!MESSAGE Unable to track file that does not exist: C:\Python27\DLLs
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\DLLs
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-21 18:24:12.895
!MESSAGE Unable to track file that does not exist: C:\Python27\lib
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-21 18:24:12.979
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\lib-tk
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\lib-tk
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-21 18:24:12.990
!MESSAGE Unable to track file that does not exist: C:\Python27
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-21 18:24:13.001
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\site-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\site-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2017-02-21 18:24:43.635
!MESSAGE java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:312)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:278)
	at org.python.pydev.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:329)
	at org.python.pydev.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:95)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:68)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:44)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:390)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SynchSystemModulesManager.java:173)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.updateStructures(SynchSystemModulesManager.java:252)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:238)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:310)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 15 more

!ENTRY org.eclipse.jdt.core 4 4 2017-02-21 18:25:38.808
!MESSAGE JavaBuilder handling ImageBuilderInternalException while building: HW7
!STACK 1
org.eclipse.core.runtime.CoreException: Could not write file: C:\Users\SaWLeaDeR\workspace\HW7\bin\demo.
	at org.eclipse.core.internal.filesystem.Policy.error(Policy.java:49)
	at org.eclipse.core.internal.filesystem.Policy.error(Policy.java:44)
	at org.eclipse.core.internal.filesystem.local.LocalFile.checkTargetIsNotWritable(LocalFile.java:95)
	at org.eclipse.core.internal.filesystem.local.LocalFile.mkdir(LocalFile.java:309)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.write(FileSystemResourceManager.java:1194)
	at org.eclipse.core.internal.resources.Folder.internalCreate(Folder.java:172)
	at org.eclipse.core.internal.resources.Folder.create(Folder.java:105)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.createFolder(AbstractImageBuilder.java:473)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder$1.visit(AbstractImageBuilder.java:257)
	at org.eclipse.core.internal.resources.Resource$1.visitElement(Resource.java:84)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:82)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:129)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:52)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.addAllSourceFiles(AbstractImageBuilder.java:222)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:52)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:256)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:175)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
!SUBENTRY 1 org.eclipse.core.filesystem 4 272 2017-02-21 18:25:38.810
!MESSAGE Could not write file: C:\Users\SaWLeaDeR\workspace\HW7\bin\demo.

!ENTRY org.epic.perleditor 4 0 2017-02-21 18:25:46.040
!MESSAGE Failed to execute command line: "perl" "-v"
!STACK 0
java.io.IOException: Cannot run program "perl" (in directory "."): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:106)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:71)
	at org.epic.core.util.PerlExecutor.execute(PerlExecutor.java:100)
	at org.epic.perleditor.PerlEditorPlugin.checkForPerlInterpreter(PerlEditorPlugin.java:262)
	at org.epic.perleditor.PerlEditorPlugin.requirePerlInterpreter(PerlEditorPlugin.java:235)
	at org.epic.core.builders.PerlBuilder.buildImpl(PerlBuilder.java:77)
	at org.epic.core.builders.PerlBuilder.build(PerlBuilder.java:63)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 21 more

!ENTRY org.epic.perleditor 4 0 2017-02-21 18:25:47.487
!MESSAGE Failed to execute command line: "perl" "-v"
!STACK 0
java.io.IOException: Cannot run program "perl" (in directory "."): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:106)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:71)
	at org.epic.core.util.PerlExecutor.execute(PerlExecutor.java:100)
	at org.epic.perleditor.PerlEditorPlugin.checkForPerlInterpreter(PerlEditorPlugin.java:262)
	at org.epic.perleditor.PerlEditorPlugin.requirePerlInterpreter(PerlEditorPlugin.java:235)
	at org.epic.core.builders.PerlBuilder.buildImpl(PerlBuilder.java:77)
	at org.epic.core.builders.PerlBuilder.build(PerlBuilder.java:63)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 21 more

!ENTRY org.epic.perleditor 4 0 2017-02-21 18:25:47.522
!MESSAGE Failed to execute command line: "perl" "-v"
!STACK 0
java.io.IOException: Cannot run program "perl" (in directory "."): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:106)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:71)
	at org.epic.core.util.PerlExecutor.execute(PerlExecutor.java:100)
	at org.epic.perleditor.PerlEditorPlugin.checkForPerlInterpreter(PerlEditorPlugin.java:262)
	at org.epic.perleditor.PerlEditorPlugin.requirePerlInterpreter(PerlEditorPlugin.java:235)
	at org.epic.core.builders.PerlBuilder.buildImpl(PerlBuilder.java:77)
	at org.epic.core.builders.PerlBuilder.build(PerlBuilder.java:63)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 21 more

!ENTRY org.epic.perleditor 4 0 2017-02-21 18:26:30.314
!MESSAGE Failed to execute command line: "perl" "-v"
!STACK 0
java.io.IOException: Cannot run program "perl" (in directory "."): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:106)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:71)
	at org.epic.core.util.PerlExecutor.execute(PerlExecutor.java:100)
	at org.epic.perleditor.PerlEditorPlugin.checkForPerlInterpreter(PerlEditorPlugin.java:262)
	at org.epic.perleditor.PerlEditorPlugin.requirePerlInterpreter(PerlEditorPlugin.java:235)
	at org.epic.core.builders.PerlBuilder.buildImpl(PerlBuilder.java:77)
	at org.epic.core.builders.PerlBuilder.build(PerlBuilder.java:63)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 21 more
!SESSION 2017-02-22 18:43:16.018 -----------------------------------------------
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=tr_TR
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.osgi 2 0 2017-02-22 18:43:48.987
!MESSAGE While loading class "org.eclipse.egit.ui.internal.ConfigurationChecker$1$1", thread "Thread[Worker-2,5,main]" timed out waiting (5041ms) for thread "Thread[main,6,main]" to finish starting bundle "org.eclipse.egit.ui_4.4.1.201607150455-r [124]". To avoid deadlock, thread "Thread[Worker-2,5,main]" is proceeding but "org.eclipse.egit.ui.internal.ConfigurationChecker$1$1" may not be fully initialized.
!STACK 0
org.osgi.framework.BundleException: Unable to acquire the state change lock for the module: osgi.identity; type="osgi.bundle"; version:Version="4.4.1.201607150455-r"; osgi.identity="org.eclipse.egit.ui"; singleton:="true" [id=124] STARTED [STARTED]
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:337)
	at org.eclipse.osgi.container.Module.start(Module.java:401)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:470)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:529)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:325)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.egit.ui.internal.ConfigurationChecker$1.run(ConfigurationChecker.java:45)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.util.concurrent.TimeoutException: Timeout after waiting 5 seconds to acquire the lock.
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:334)
	... 13 more
Root exception:
java.util.concurrent.TimeoutException: Timeout after waiting 5 seconds to acquire the lock.
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:334)
	at org.eclipse.osgi.container.Module.start(Module.java:401)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:470)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:529)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:325)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.egit.ui.internal.ConfigurationChecker$1.run(ConfigurationChecker.java:45)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.egit.ui 2 0 2017-02-22 18:44:25.733
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\SaWLeaDeR'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.eclipse.ui.workbench 4 2 2017-02-22 18:44:42.371
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.ExceptionInInitializerError
	at org.eclipse.oomph.p2.internal.core.AgentImpl.initializeProvisioningAgent(AgentImpl.java:503)
	at org.eclipse.oomph.p2.internal.core.AgentManagerImpl.getCurrentAgent(AgentManagerImpl.java:188)
	at org.eclipse.oomph.p2.core.P2Util.getCurrentProvisioningAgent(P2Util.java:71)
	at org.eclipse.oomph.setup.internal.core.util.SetupCoreUtil.<clinit>(SetupCoreUtil.java:136)
	at org.eclipse.oomph.setup.ui.recorder.RecorderManager.<clinit>(RecorderManager.java:119)
	at org.eclipse.oomph.setup.ui.SetupUIPlugin.performStartup(SetupUIPlugin.java:205)
	at org.eclipse.oomph.setup.ui.EarlyStartup.earlyStartup(EarlyStartup.java:22)
	at org.eclipse.ui.internal.EarlyStartupRunnable.runEarlyStartup(EarlyStartupRunnable.java:77)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:53)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.Workbench$55.run(Workbench.java:2835)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.NullPointerException
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Artifact.<clinit>(CachingRepositoryManager.java:507)
	... 12 more

!ENTRY org.eclipse.ui 4 0 2017-02-22 18:44:42.526
!MESSAGE Unable to execute early startup code for the org.eclipse.ui.IStartup extension contributed by the 'org.eclipse.oomph.setup.ui' plug-in.
!STACK 0
java.lang.ExceptionInInitializerError
	at org.eclipse.oomph.p2.internal.core.AgentImpl.initializeProvisioningAgent(AgentImpl.java:503)
	at org.eclipse.oomph.p2.internal.core.AgentManagerImpl.getCurrentAgent(AgentManagerImpl.java:188)
	at org.eclipse.oomph.p2.core.P2Util.getCurrentProvisioningAgent(P2Util.java:71)
	at org.eclipse.oomph.setup.internal.core.util.SetupCoreUtil.<clinit>(SetupCoreUtil.java:136)
	at org.eclipse.oomph.setup.ui.recorder.RecorderManager.<clinit>(RecorderManager.java:119)
	at org.eclipse.oomph.setup.ui.SetupUIPlugin.performStartup(SetupUIPlugin.java:205)
	at org.eclipse.oomph.setup.ui.EarlyStartup.earlyStartup(EarlyStartup.java:22)
	at org.eclipse.ui.internal.EarlyStartupRunnable.runEarlyStartup(EarlyStartupRunnable.java:77)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:53)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.Workbench$55.run(Workbench.java:2835)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.NullPointerException
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Artifact.<clinit>(CachingRepositoryManager.java:507)
	... 12 more
!SESSION 2017-02-24 12:22:10.571 -----------------------------------------------
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=tr_TR
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.egit.ui 2 0 2017-02-24 12:23:02.236
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\SaWLeaDeR'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.python.pydev.shared_core 1 1 2017-02-24 12:24:09.164
!MESSAGE Unable to track file that does not exist: C:\Python27\DLLs
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\DLLs
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-24 12:24:10.572
!MESSAGE Unable to track file that does not exist: C:\Python27\lib
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-24 12:24:10.595
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\lib-tk
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\lib-tk
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-24 12:24:10.608
!MESSAGE Unable to track file that does not exist: C:\Python27
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-24 12:24:10.652
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\site-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\site-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2017-02-24 12:24:41.209
!MESSAGE java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:312)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:278)
	at org.python.pydev.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:329)
	at org.python.pydev.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:95)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:68)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:44)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:390)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SynchSystemModulesManager.java:173)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.updateStructures(SynchSystemModulesManager.java:252)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:238)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:310)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 15 more
!SESSION 2017-02-26 15:30:26.031 -----------------------------------------------
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=tr_TR
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.egit.ui 2 0 2017-02-26 15:31:25.294
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\SaWLeaDeR'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.python.pydev.shared_core 1 1 2017-02-26 15:32:26.980
!MESSAGE Unable to track file that does not exist: C:\Python27\DLLs
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\DLLs
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-26 15:32:27.024
!MESSAGE Unable to track file that does not exist: C:\Python27\lib
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-26 15:32:27.036
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\lib-tk
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\lib-tk
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-26 15:32:27.051
!MESSAGE Unable to track file that does not exist: C:\Python27
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-26 15:32:27.060
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\site-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\site-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.epic.perleditor 4 0 2017-02-26 15:32:45.537
!MESSAGE Failed to execute command line: "perl" "-v"
!STACK 0
java.io.IOException: Cannot run program "perl" (in directory "."): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:106)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:71)
	at org.epic.core.util.PerlExecutor.execute(PerlExecutor.java:100)
	at org.epic.perleditor.PerlEditorPlugin.checkForPerlInterpreter(PerlEditorPlugin.java:262)
	at org.epic.perleditor.PerlEditorPlugin.requirePerlInterpreter(PerlEditorPlugin.java:235)
	at org.epic.core.builders.PerlBuilder.buildImpl(PerlBuilder.java:77)
	at org.epic.core.builders.PerlBuilder.build(PerlBuilder.java:63)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 21 more

!ENTRY org.epic.perleditor 4 0 2017-02-26 15:32:47.122
!MESSAGE Failed to execute command line: "perl" "-v"
!STACK 0
java.io.IOException: Cannot run program "perl" (in directory "."): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:106)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:71)
	at org.epic.core.util.PerlExecutor.execute(PerlExecutor.java:100)
	at org.epic.perleditor.PerlEditorPlugin.checkForPerlInterpreter(PerlEditorPlugin.java:262)
	at org.epic.perleditor.PerlEditorPlugin.requirePerlInterpreter(PerlEditorPlugin.java:235)
	at org.epic.core.builders.PerlBuilder.buildImpl(PerlBuilder.java:77)
	at org.epic.core.builders.PerlBuilder.build(PerlBuilder.java:63)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 21 more

!ENTRY org.epic.perleditor 4 0 2017-02-26 15:32:47.258
!MESSAGE Failed to execute command line: "perl" "-v"
!STACK 0
java.io.IOException: Cannot run program "perl" (in directory "."): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:106)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:71)
	at org.epic.core.util.PerlExecutor.execute(PerlExecutor.java:100)
	at org.epic.perleditor.PerlEditorPlugin.checkForPerlInterpreter(PerlEditorPlugin.java:262)
	at org.epic.perleditor.PerlEditorPlugin.requirePerlInterpreter(PerlEditorPlugin.java:235)
	at org.epic.core.builders.PerlBuilder.buildImpl(PerlBuilder.java:77)
	at org.epic.core.builders.PerlBuilder.build(PerlBuilder.java:63)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 21 more

!ENTRY org.python.pydev.shared_core 4 4 2017-02-26 15:32:57.372
!MESSAGE java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:312)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:278)
	at org.python.pydev.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:329)
	at org.python.pydev.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:95)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:68)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:44)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:390)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SynchSystemModulesManager.java:173)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.updateStructures(SynchSystemModulesManager.java:252)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:238)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:310)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 15 more

!ENTRY org.epic.perleditor 4 0 2017-02-26 15:33:01.848
!MESSAGE Failed to execute command line: "perl" "-v"
!STACK 0
java.io.IOException: Cannot run program "perl" (in directory "."): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:106)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:71)
	at org.epic.core.util.PerlExecutor.execute(PerlExecutor.java:100)
	at org.epic.perleditor.PerlEditorPlugin.checkForPerlInterpreter(PerlEditorPlugin.java:262)
	at org.epic.perleditor.PerlEditorPlugin.requirePerlInterpreter(PerlEditorPlugin.java:235)
	at org.epic.core.builders.PerlBuilder.buildImpl(PerlBuilder.java:77)
	at org.epic.core.builders.PerlBuilder.build(PerlBuilder.java:63)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 21 more

!ENTRY org.eclipse.equinox.p2.metadata.repository 4 1000 2017-02-26 15:56:44.793
!MESSAGE No repository found at http://download.eclipse.org/tools/cdt/releases/eclipse9.2.

!ENTRY org.eclipse.equinox.p2.metadata.repository 4 1000 2017-02-26 15:56:47.307
!MESSAGE No repository found at http://download.eclipse.org/tools/cdt/releases/eclipse3.1.

!ENTRY org.epic.perleditor 4 0 2017-02-26 16:44:41.354
!MESSAGE Failed to execute command line: "perl" "-v"
!STACK 0
java.io.IOException: Cannot run program "perl" (in directory "."): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:106)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:71)
	at org.epic.core.util.PerlExecutor.execute(PerlExecutor.java:100)
	at org.epic.perleditor.PerlEditorPlugin.checkForPerlInterpreter(PerlEditorPlugin.java:262)
	at org.epic.perleditor.PerlEditorPlugin.requirePerlInterpreter(PerlEditorPlugin.java:235)
	at org.epic.core.builders.PerlBuilder.buildImpl(PerlBuilder.java:77)
	at org.epic.core.builders.PerlBuilder.build(PerlBuilder.java:63)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 21 more

!ENTRY org.epic.perleditor 4 0 2017-02-26 16:44:52.727
!MESSAGE Failed to execute command line: "perl" "-v"
!STACK 0
java.io.IOException: Cannot run program "perl" (in directory "."): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:106)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:71)
	at org.epic.core.util.PerlExecutor.execute(PerlExecutor.java:100)
	at org.epic.perleditor.PerlEditorPlugin.checkForPerlInterpreter(PerlEditorPlugin.java:262)
	at org.epic.perleditor.PerlEditorPlugin.requirePerlInterpreter(PerlEditorPlugin.java:235)
	at org.epic.core.builders.PerlBuilder.buildImpl(PerlBuilder.java:77)
	at org.epic.core.builders.PerlBuilder.build(PerlBuilder.java:63)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 21 more

!ENTRY org.epic.perleditor 4 0 2017-02-26 16:45:04.994
!MESSAGE Failed to execute command line: "perl" "-v"
!STACK 0
java.io.IOException: Cannot run program "perl" (in directory "."): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:106)
	at org.epic.core.util.ProcessExecutor.execute(ProcessExecutor.java:71)
	at org.epic.core.util.PerlExecutor.execute(PerlExecutor.java:100)
	at org.epic.perleditor.PerlEditorPlugin.checkForPerlInterpreter(PerlEditorPlugin.java:262)
	at org.epic.perleditor.PerlEditorPlugin.requirePerlInterpreter(PerlEditorPlugin.java:235)
	at org.epic.core.builders.PerlBuilder.buildImpl(PerlBuilder.java:77)
	at org.epic.core.builders.PerlBuilder.build(PerlBuilder.java:63)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 21 more
!SESSION 2017-02-26 19:19:21.669 -----------------------------------------------
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=tr_TR
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.egit.ui 2 0 2017-02-26 19:19:42.000
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\SaWLeaDeR'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.python.pydev.shared_core 1 1 2017-02-26 19:19:51.845
!MESSAGE Unable to track file that does not exist: C:\Python27\DLLs
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\DLLs
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-26 19:19:52.365
!MESSAGE Unable to track file that does not exist: C:\Python27\lib
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-26 19:19:52.375
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\lib-tk
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\lib-tk
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-26 19:19:52.384
!MESSAGE Unable to track file that does not exist: C:\Python27
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 1 1 2017-02-26 19:19:52.404
!MESSAGE Unable to track file that does not exist: C:\Python27\lib\site-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Python27\lib\site-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2017-02-26 19:20:22.517
!MESSAGE java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:312)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:278)
	at org.python.pydev.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:329)
	at org.python.pydev.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:95)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:68)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:44)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:390)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SynchSystemModulesManager.java:173)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.updateStructures(SynchSystemModulesManager.java:252)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:238)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Cannot run program "C:\Python27\python.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:103)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:310)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 15 more

!ENTRY org.eclipse.equinox.p2.metadata.repository 4 1000 2017-02-26 19:39:46.607
!MESSAGE No repository found at http://download.eclipse.org/tools/cdt/releases/eclipse9.2.

!ENTRY org.eclipse.equinox.p2.metadata.repository 4 1000 2017-02-26 19:39:50.797
!MESSAGE No repository found at http://download.eclipse.org/tools/cdt/releases/eclipse3.1.
!SESSION 2017-03-03 22:38:32.113 -----------------------------------------------
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=tr_TR
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.egit.ui 2 0 2017-03-03 22:39:46.037
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\SaWLeaDeR'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.
!SESSION 2017-03-07 16:55:44.435 -----------------------------------------------
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=tr_TR
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.equinox.app 4 2 2017-03-07 16:56:34.918
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.equinox.app".
!STACK 0
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:354)
	at org.eclipse.swt.widgets.Shell.close(Shell.java:545)
	at org.eclipse.ui.splash.AbstractSplashHandler.dispose(AbstractSplashHandler.java:63)
	at org.eclipse.ui.splash.BasicSplashHandler.dispose(BasicSplashHandler.java:183)
	at org.eclipse.ui.internal.Workbench$6$1.applicationRunning(Workbench.java:859)
	at org.eclipse.equinox.internal.app.EclipseAppHandle$1.run(EclipseAppHandle.java:268)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.applicationRunning(EclipseAppHandle.java:258)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1068)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

!ENTRY org.eclipse.egit.ui 2 0 2017-03-07 16:56:36.539
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\SaWLeaDeR'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.eclipse.core.jobs 2 2 2017-03-07 16:58:53.089
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.eclipse.epp.internal.logging.aeri.ide.server.mars.ProblemsDatabaseProblemsHistory$UpdateIndexJob
